Add grid-local-quadratic-2023-05 acq probability model
sot/chandra_models pull request #106
Opened 2023-04-27 17:26 UTC by taldcroft

## Description

This adds the new acquisition probability model that was developed in https://github.com/sot/aca_stats/pull/16.

Closes #99 

## Functional testing

In a ska3-dev environment with the current master of chandra_aca etc:
```
In [1]: os.environ["THERMAL_MODELS_DIR_FOR_MATLAB_TOOLS_SW"]
Out[1]: '/Users/aldcroft/git/chandra_models'

In [2]: from ska_helpers.paths import chandra_models_repo_path
   ...: 
   ...: chandra_models_repo_path()
   ...: from chandra_aca.star_probs import acq_success_prob
   ...: 

In [3]: acq_success_prob(mag=9.75, halfwidth=140, t_ccd=0)  # Flight model
   ...: 
Out[3]: 0.08876371372991076

In [4]: acq_success_prob(  # New model
   ...:     mag=9.75, halfwidth=140, t_ccd=0, model="grid-local-quadratic-2023-05"
   ...: )
   ...: 
Out[4]: 0.40033623318863376
```
These values match expectation based on this plot from https://github.com/sot/aca_stats/blob/master/fit_acq_model-2023-05-local-quadratic.ipynb, where the x-axis ticks are at -15, -10, -5, and 0 C respectively and the y-axis goes from 0.0 to 1.0.

<img width="151" alt="image" src="https://user-images.githubusercontent.com/348089/234940219-dde1f9f6-4c8a-4339-8bfa-3e3fba437654.png">

2023-06-16 20:06 UTC, jeanconn requested changes
I'm a little concerned this is a model fit with agasc_file agasc1p8rc1.h5 , and I don't know where that is or what was in it at the time of the fit.  Overall that's probably fine but I think requires that we archive that file someplace.

2023-06-17 10:22 UTC, taldcroft commented
> I'm a little concerned this is a model fit with agasc_file agasc1p8rc1.h5 

The mags in rc1 will be identical to the final AGASC 1.8 since no more changes to mag estimation algorithm are planned. Any small changes in final star correlations will not impact the probabilities at a level that is observable. So I don't understand what value there will be in archiving that file since it will never get used again.

2023-06-18 00:09 UTC, jeanconn commented
OK, if the rc1 file is the latest-draft-mags that are expected for 1.8 that sounds fine.

2023-06-18 00:09 UTC, jeanconn approved these changes

2023-06-27 13:55 UTC, merged